services:
  - type: worker
    name: booktopia-bot
    env: node
    rootDir: booktopia-bot
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
